# 保留治疗事件与消费者的公开中文证据文字，数值和区间由独立计算核心提供。
TREATMENT_TEXT = {'oneiroi_awaken2_team': {'target_scope': 'team',
                          'evidence_kind': 'confirmed_other_character_e',
                          'confidence': '低',
                          'inference_basis': '일로이 2각성은 현재 프로젝트에서 확인된 기준에 따라 다른 캐릭터의 실제 E 동작으로 발동되며, 재사용 대기시간은 유효 전투 시간 5'
                                             '초입니다; 세 가지 무작위 소환 모두 팀 전체 치료를 한 번만 생성하고 소환 공격 hit '
                                             '수만큼 복제하지 않습니다. 정식 내보내기가 완전한 스케줄 시점을 노출하지 않아 임시로 발동 E 동작 시작점에 고정합니다.',
                          'amount_basis': '일로이 정산 시 공격력 × 120%. 현재 이벤트 수치는 알 수 없음으로 유지합니다.'},
 'oneiroi_q_period': {'target_scope': 'team',
                      'evidence_kind': 'formal_skill_animation',
                      'confidence': '中',
                      'inference_basis': '일로이 Q 지속 치료는 정식으로 14초 지속, 주기 1초이며 부여 시 즉시 실행되지 않습니다. 주기와 지속 시간은 시간 정지를 제외한 활성 시계를 사용합니다.'},
 'edgar_hold_e_segment': {'target_scope': 'lowest_hp_team_member',
                          'evidence_kind': 'formal_damage_segment_binding',
                          'confidence': '中',
                          'inference_basis': '에드가 E 길게 누르기는 실제 피해 단계마다 치유를 한 번씩 함께 적용합니다. 전투 리포트에 실제로 존재하는 길게 누르기 단계만 생성하며 이론상의 7단계를 채우지 않습니다.',
                          'amount_basis': '스킬 레벨 고정값 + 정산 시 치유 대상 최대 HP × '
                                          '스킬 레벨 비율. 현재 축에는 치유 대상과 캐릭터 HP가 없어 수치는 알 수 없음으로 유지됩니다.'},
 'shinku_effect5_rage_e': {'target_scope': 'self',
                           'evidence_kind': 'formal_rage_e_damage_binding',
                           'confidence': '中',
                           'inference_basis': '신쿠 5각성은 승천의 적이 E를 대체한 두 번째 단계의 정식 피해 항목이 실제로 나타날 때만 자가 치유를 한 번 생성합니다; 같은 시점의 다중 대상 hit'
                                              '는 출처 측 치유를 중복 생성하지 않습니다.'},
 'kuhara_effect2_q_settlement': {'target_scope': 'team',
                                 'evidence_kind': 'formal_q_settlement_hit',
                                 'confidence': '中',
                                 'inference_basis': '구원 2각성은 Q로 능동 청산한 실제 장미 서약 정산 시에만 파티 전체를 치유합니다; A 길게 누르기 '
                                                    '청산과 자연 만료는 치료를 생성하지 않습니다. 다중 대상은 각자 관측된 청산 이벤트별로 독립 출처를 유지합니다.',
                                 'amount_basis': '해당 장미 서약 대상 누적 총 피해 × 5%. 현재 축에는 치료 실행기가 읽은 누적값이 저장되지 않아 수치는 알 수 없음으로 유지됩니다.'},
 'lacrimosa_effect5_period': {'target_scope': 'self',
                              'evidence_kind': 'formal_period_and_damage_window',
                              'confidence': '中',
                              'inference_basis': '라크리모사 5각성은 유효 전투 3초마다 이전 창의 악몽 본체 피해를 합산하고, 합계의 1.5%를 '
                                                 '현재 통합 정산 규칙에 따라 내림해 자가 치유합니다. 양수 악몽 피해가 없는 창에서는 출처 측 치유 브로드캐스트를 추론하지 않습니다.'},
 'edgar_q_field_period': {'target_scope': 'active_character',
                          'evidence_kind': 'formal_field_period',
                          'confidence': '中',
                          'inference_basis': '에드가 Q 영역은 생성 후 유효 전투 1초가 지나면 매초 치유를 시작합니다. 진리의 열쇠는 이번 전투에서 추론된 에드가 E/QTE'
                                             '와 1각성 아군 QTE 동작으로 최대 3개까지 누적되고, Q 시 소모해 기본 10'
                                             '틱을 열쇠 1개당 연장합니다. 다른 캐릭터의 동작이 감지되면 이후 영역 치유를 중단합니다.',
                          'amount_basis': '스킬 레벨 고정값 + 현재 치유 대상 캐릭터 최대 HP × 스킬 레벨 비율. 현재 축에는 치유 대상과 캐릭터 HP가 없어 수치는 알 수 없음으로 유지됩니다.'},
 'zankou_effect3_huo_period': {'target_scope': 'self',
                               'evidence_kind': 'formal_huo_interval_and_period',
                               'confidence': '中',
                               'inference_basis': '잔홍 3각성 치료는 「惑」 상태의 1초 '
                                                  '정식 주기로 실행됩니다. 재구성된 「惑」 보유 구간 내에서만 시간 정지를 제외한 활동 시계에 따라 생성됩니다. 현재 축에는 플레이어 사망 이벤트가 없어 1각성 상시 「惑」 상태는 전투 종료까지 투영됩니다.'},
 'oneiroi_e_tap': {'target_scope': 'team',
                   'evidence_kind': 'formal_skill_animation',
                   'confidence': '中',
                   'inference_basis': '일로이 정식 스킬은 애니메이션 이벤트 E.1에서 치료를 부여하며, 이벤트 시점은 동작 시작점과 정식 애니메이션 Notify 오프셋에서 파생됩니다.'},
 'oneiroi_qte': {'target_scope': 'team',
                 'evidence_kind': 'formal_skill_animation',
                 'confidence': '中',
                 'inference_basis': '일로이 정식 스킬은 애니메이션 이벤트 QTE.2에서 치료를 부여하며, 이벤트 시점은 동작 시작점과 정식 애니메이션 Notify 오프셋에서 파생됩니다.'},
 'oneiroi_q': {'target_scope': 'team',
               'evidence_kind': 'formal_skill_animation',
               'confidence': '中',
               'inference_basis': '일로이 정식 스킬은 애니메이션 이벤트 UltraSkill.1에서 치료를 부여하며, 이벤트 시점은 동작 시작점과 정식 애니메이션 Notify 오프셋에서 파생됩니다.'}}

TREATMENT_BUFF_TEXT = {'oneiroi-passive-2': {'buff_asset_path': '/Game/Blueprints/Abilities/Player/Ability_075_Oneiroi/PassiveEffect/Buff_Oneiroi075_Passive2_DamUP',
                       'buff_name': '交感性神经系统',
                       'source_effect_definition_id': 'character_passive:1075:GA_Oneiroi_Passive_2',
                       'target_scope': 'team',
                       'trigger_event_type': 'BUFF_EVENT_TREATMENT',
                       'inference_basis': '정식 패시브가 BUFF_EVENT_TREATMENT를 감시하며, 출처 측 치료 이벤트마다 팀 전체의 20초 '
                                          '방어 무시를 갱신합니다. HP가 가득 찼거나 유효 치료가 0이어도 치료 이벤트로 간주합니다.',
                       'property_id': 'DefIgnore',
                       'magnitude_kind': 'formal_character_passive',
                       'calculation_asset_path': '/Game/Blueprints/Abilities/Calculation/Oneiroi/Calc_Oneiroi_Passive2_DefIgnore'},
 'oneiroi-e-attack': {'buff_asset_path': '/Game/Blueprints/Abilities/Player/Ability_075_Oneiroi/Buff/Buff_Oneiroi_Skill_AtkUP',
                      'buff_name': '일로이 E: 팀 전체 공격력',
                      'source_effect_definition_id': 'character_skill:1075:GA_Oneiroi_Skill',
                      'target_scope': 'team',
                      'trigger_event_type': 'BUFF_EVENT_TREATMENT|oneiroi_e_tap',
                      'inference_basis': '일로이 E 짧게 누르기의 정식 치료 이벤트는 팀 전체 고정 공격력도 함께 부여합니다. 수치: min(출처 기본 공격력 × 20%, 500), 20'
                                         '초 지속.',
                      'property_id': 'AtkAdd',
                      'magnitude_kind': 'formal_source_atk_base_calculation',
                      'calculation_asset_path': '/Game/DataTable/Skill/GlobalCharacterData/DT_OneiroiEffectFigure:Oneiroi_Skill_AtkAdd'},
 'oneiroi-effect-5': {'buff_asset_path': '/Game/Blueprints/Abilities/Player/Ability_075_Oneiroi/PassiveEffect/Buff_Oneiroi075_Passive2_LV4_DamUP',
                      'buff_name': '清晰',
                      'source_effect_definition_id': 'character_awaken:1075:Effect5',
                      'target_scope': 'team',
                      'trigger_event_type': 'BUFF_EVENT_TREATMENT',
                      'inference_basis': '일로이 5각성은 정식 치료 이벤트마다 팀 전체 고정 공격력을 갱신합니다. 수치: min(출처 기본 공격력 × 15%, 500), 20'
                                         '초 지속.',
                      'property_id': 'AtkAdd',
                      'magnitude_kind': 'formal_source_atk_base_calculation',
                      'calculation_asset_path': '/Game/Blueprints/Abilities/Calculation/Oneiroi/Calc_Oneiroi_Passive2_AtkAddLV4'}}
